version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
     
  redis:
    image: redis:7.2
    container_name: redis_container_mongoapi
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_mongoapi:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  mongo_data:
  redis_mongoapi: