version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: